// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ui/Score.h>
extern hl_type t$_i32;
String Std_string(vdynamic*);
String h2d_Text_set_text(h2d__Text,String);
#include <_std/Game.h>
#include <h2d/Object.h>
#include <h2d/Align.h>
#include <h2d/Scene.h>
h2d__Font hxd_res_DefaultFont_get(void);
extern $Game g$_Game;
extern hl_type t$h2d_Text;
void h2d_Text_new(h2d__Text,h2d__Font,h2d__Object);
extern venum* g$h2d_Align_Right;
venum* h2d_Text_set_textAlign(h2d__Text,venum*);
#include <h2d/Layers.h>
void h2d_Layers_addChild(h2d__Layers,h2d__Object);

int ui_Score_getScore(ui__Score r0) {
	int r1;
	r1 = r0->currentScore;
	return r1;
}

void ui_Score_setScore(ui__Score r0,int r1) {
	String r3;
	h2d__Text r4;
	vdynamic *r5;
	int r2;
	r0->currentScore = r1;
	r4 = r0->tf;
	if( r4 == NULL ) hl_null_access();
	r2 = r0->currentScore;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r2;
	r3 = Std_string(r5);
	r3 = h2d_Text_set_text(r4,r3);
	return;
}

void ui_Score_addScore(ui__Score r0,int r1) {
	String r3;
	h2d__Text r4;
	vdynamic *r5;
	int r2;
	r2 = r0->currentScore;
	r2 = r2 + r1;
	r0->currentScore = r2;
	r4 = r0->tf;
	if( r4 == NULL ) hl_null_access();
	r2 = r0->currentScore;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r2;
	r3 = Std_string(r5);
	r3 = h2d_Text_set_text(r4,r3);
	return;
}

void ui_Score_removeScore(ui__Score r0,int r1) {
	String r3;
	h2d__Text r4;
	vdynamic *r5;
	int r2;
	r2 = r0->currentScore;
	r2 = r2 - r1;
	r0->currentScore = r2;
	r4 = r0->tf;
	if( r4 == NULL ) hl_null_access();
	r2 = r0->currentScore;
	r5 = hl_alloc_dynamic(&t$_i32);
	r5->v.i = r2;
	r3 = Std_string(r5);
	r3 = h2d_Text_set_text(r4,r3);
	return;
}

void ui_Score_new(ui__Score r0,int r1,int r2) {
	String r13;
	$Game r6;
	Game r5;
	venum *r12;
	bool r10;
	h2d__Object r8;
	h2d__Text r7;
	h2d__Font r4;
	double r11;
	h2d__Scene r15;
	vdynamic *r14;
	int r3;
	r3 = 0;
	r0->currentScore = r3;
	r4 = hxd_res_DefaultFont_get();
	r0->font = r4;
	r6 = ($Game)g$_Game;
	r5 = r6->inst;
	r0->game = r5;
	r7 = (h2d__Text)hl_alloc_obj(&t$h2d_Text);
	r4 = r0->font;
	r8 = NULL;
	h2d_Text_new(r7,r4,r8);
	r0->tf = r7;
	r7 = r0->tf;
	if( r7 == NULL ) hl_null_access();
	r10 = true;
	r7->posChanged = r10;
	r11 = 4.;
	r7->scaleX = r11;
	r10 = true;
	r7->posChanged = r10;
	r11 = 4.;
	r7->scaleY = r11;
	r7 = r0->tf;
	if( r7 == NULL ) hl_null_access();
	r10 = true;
	r7->posChanged = r10;
	r11 = (double)r1;
	r7->x = r11;
	r7 = r0->tf;
	if( r7 == NULL ) hl_null_access();
	r10 = true;
	r7->posChanged = r10;
	r11 = (double)r2;
	r7->y = r11;
	r7 = r0->tf;
	if( r7 == NULL ) hl_null_access();
	r12 = (venum*)g$h2d_Align_Right;
	r12 = h2d_Text_set_textAlign(r7,r12);
	r7 = r0->tf;
	if( r7 == NULL ) hl_null_access();
	r3 = r0->currentScore;
	r14 = hl_alloc_dynamic(&t$_i32);
	r14->v.i = r3;
	r13 = Std_string(r14);
	r13 = h2d_Text_set_text(r7,r13);
	r5 = r0->game;
	if( r5 == NULL ) hl_null_access();
	r15 = r5->scene;
	if( r15 == NULL ) hl_null_access();
	r7 = r0->tf;
	h2d_Layers_addChild(((h2d__Layers)r15),((h2d__Object)r7));
	return;
}

