// Generated by HLC 4.1.4 (HL v5)
#ifndef INC_ent__Actor
#define INC_ent__Actor
typedef struct _ent__$Actor *ent__$Actor;
typedef struct _ent__Actor *ent__Actor;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <_std/Game.h>
#include <h2d/Object.h>


struct _ent__$Actor {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _ent__Actor {
	hl_type *$type;
	Game game;
	double x;
	double y;
	double scale;
	h2d__Object spr;
};
#endif

