// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ent/Actor.h>
#include <_std/Game.h>
#include <hl/types/ArrayObj.h>
extern $Game g$_Game;
extern hl_type t$h2d_Object;
void h2d_Object_new(h2d__Object,h2d__Object);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
#include <ent/Wall.h>
#include <h2d/col/Bounds.h>
extern hl_type t$ent_Wall;
extern hl_type t$_dyn;
h2d__Object ent_Actor_getSprite(ent__Actor);
h2d__col__Bounds h2d_Object_getBounds(h2d__Object,h2d__Object,h2d__col__Bounds);
#include <h2d/Scene.h>
#include <h2d/Layers.h>
void h2d_Layers_removeChild(h2d__Layers,h2d__Object);
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);

void ent_Actor_new(ent__Actor r0,double* r1,double* r2,double* r3) {
	$Game r8;
	hl__types__ArrayObj r14;
	Game r7;
	bool r12;
	h2d__Object r9, r10;
	double r4, r5, r6;
	int r13;
	if( r1 ) goto label$6d1647b_1_3;
	r4 = 0.;
	goto label$6d1647b_1_4;
	label$6d1647b_1_3:
	r4 = *r1;
	label$6d1647b_1_4:
	if( r2 ) goto label$6d1647b_1_7;
	r5 = 0.;
	goto label$6d1647b_1_8;
	label$6d1647b_1_7:
	r5 = *r2;
	label$6d1647b_1_8:
	if( r3 ) goto label$6d1647b_1_11;
	r6 = 1.;
	goto label$6d1647b_1_12;
	label$6d1647b_1_11:
	r6 = *r3;
	label$6d1647b_1_12:
	r8 = ($Game)g$_Game;
	r7 = r8->inst;
	r0->game = r7;
	r0->x = r4;
	r0->y = r5;
	r0->scale = r6;
	r9 = (h2d__Object)hl_alloc_obj(&t$h2d_Object);
	r10 = NULL;
	h2d_Object_new(r9,r10);
	r0->spr = r9;
	r9 = r0->spr;
	if( r9 == NULL ) hl_null_access();
	r12 = true;
	r9->posChanged = r12;
	r9->x = r4;
	r9 = r0->spr;
	if( r9 == NULL ) hl_null_access();
	r12 = true;
	r9->posChanged = r12;
	r9->y = r5;
	r9 = r0->spr;
	if( r9 == NULL ) hl_null_access();
	r12 = true;
	r9->posChanged = r12;
	r9->scaleX = r6;
	r12 = true;
	r9->posChanged = r12;
	r9->scaleY = r6;
	r7 = r0->game;
	if( r7 == NULL ) hl_null_access();
	r14 = r7->entities;
	if( r14 == NULL ) hl_null_access();
	r13 = hl_types_ArrayObj_push(r14,((vdynamic*)r0));
	return;
}

void ent_Actor_init(ent__Actor r0) {
	return;
}

ent__Wall ent_Actor_isWallHit(ent__Actor r0) {
	h2d__col__Bounds r9, r12;
	Game r3;
	hl__types__ArrayObj r2;
	h2d__Object r10, r11;
	ent__Wall r5, r8;
	double r13, r14;
	vdynamic *r6;
	varray *r7;
	int r1, r4;
	r1 = 0;
	r3 = r0->game;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->walls;
	label$6d1647b_3_4:
	if( r2 == NULL ) hl_null_access();
	r4 = r2->length;
	if( r1 >= r4 ) goto label$6d1647b_3_46;
	r4 = r2->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$6d1647b_3_12;
	r5 = NULL;
	goto label$6d1647b_3_18;
	label$6d1647b_3_12:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r1];
	r5 = (ent__Wall)r6;
	r8 = (ent__Wall)hl_dyn_castp(&r6,&t$_dyn,&t$ent_Wall);
	if( r5 == r8 ) goto label$6d1647b_3_18;
	hl_assert();
	label$6d1647b_3_18:
	++r1;
	r10 = ent_Actor_getSprite(r0);
	if( r10 == NULL ) hl_null_access();
	r11 = NULL;
	r9 = NULL;
	r9 = h2d_Object_getBounds(r10,r11,r9);
	if( r5 == NULL ) hl_null_access();
	r10 = ent_Actor_getSprite(((ent__Actor)r5));
	if( r10 == NULL ) hl_null_access();
	r11 = NULL;
	r12 = NULL;
	r12 = h2d_Object_getBounds(r10,r11,r12);
	if( r9 == NULL ) hl_null_access();
	r13 = r9->xMin;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->xMax;
	if( r14 < r13 ) goto label$6d1647b_3_45;
	r13 = r9->yMin;
	r14 = r12->yMax;
	if( r14 < r13 ) goto label$6d1647b_3_45;
	r13 = r9->xMax;
	r14 = r12->xMin;
	if( r13 < r14 ) goto label$6d1647b_3_45;
	r13 = r9->yMax;
	r14 = r12->yMin;
	if( r13 < r14 ) goto label$6d1647b_3_45;
	return r5;
	label$6d1647b_3_45:
	goto label$6d1647b_3_4;
	label$6d1647b_3_46:
	r5 = NULL;
	return r5;
}

void ent_Actor_destroy(ent__Actor r0) {
	hl__types__ArrayObj r6;
	Game r3;
	bool r5;
	h2d__Object r4;
	h2d__Scene r2;
	r3 = r0->game;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->scene;
	if( r2 == NULL ) hl_null_access();
	r4 = ent_Actor_getSprite(r0);
	h2d_Layers_removeChild(((h2d__Layers)r2),r4);
	r3 = r0->game;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->entities;
	if( r6 == NULL ) hl_null_access();
	r5 = hl_types_ArrayObj_remove(r6,((vdynamic*)r0));
	return;
}

h2d__Object ent_Actor_getSprite(ent__Actor r0) {
	h2d__Object r1;
	r1 = r0->spr;
	return r1;
}

void ent_Actor_setPosition(ent__Actor r0,double r1,double r2) {
	r0->x = r1;
	r0->y = r2;
	return;
}

void ent_Actor_update(ent__Actor r0,double r1) {
	bool r7;
	h2d__Object r2;
	double r4, r6;
	int r5;
	r2 = r0->spr;
	r4 = r0->x;
	r5 = (int)r4;
	r6 = (double)r5;
	if( r2 == NULL ) hl_null_access();
	r7 = true;
	r2->posChanged = r7;
	r2->x = r6;
	r2 = r0->spr;
	r4 = r0->y;
	r5 = (int)r4;
	r6 = (double)r5;
	if( r2 == NULL ) hl_null_access();
	r7 = true;
	r2->posChanged = r7;
	r2->y = r6;
	return;
}

