// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ent/Bullet.h>
#include <h2d/Align.h>
extern hl_type t$h2d_Text;
void h2d_Text_new(h2d__Text,h2d__Font,h2d__Object);
extern venum* g$h2d_Align_Left;
venum* h2d_Text_set_textAlign(h2d__Text,venum*);
#include <h2d/col/Bounds.h>
#include <ent/Player.h>
h2d__Object ent_Actor_getSprite(ent__Actor);
h2d__col__Bounds h2d_Object_getBounds(h2d__Object,h2d__Object,h2d__col__Bounds);
#include <hl/types/ArrayObj.h>
#include <ent/Invader.h>
extern hl_type t$ent_Invader;
extern hl_type t$_dyn;
void ent_Actor_destroy(ent__Actor);
#include <ent/Wall.h>
#include <ui/Score.h>
#include <h2d/Scene.h>
extern ent__$Bullet g$_ent_Bullet;
ent__Wall ent_Actor_isWallHit(ent__Actor);
void ent_Wall_damage(ent__Wall);
void ui_Score_addScore(ui__Score,int);
void ent_Invader_destroy(ent__Invader);
void ent_Player_destroy(ent__Player);
void ent_Actor_update(ent__Actor,double);
#include <h2d/Tile.h>
h2d__Font hxd_res_DefaultFont_get(void);
void ent_Actor_new(ent__Actor,double*,double*,double*);
extern hl_type t$h2d_Bitmap;
void h2d_Bitmap_new(h2d__Bitmap,h2d__Tile,h2d__Object);

void ent_Bullet_init(ent__Bullet r0) {
	venum *r5;
	h2d__Object r3;
	h2d__Font r2;
	h2d__Text r1;
	r1 = (h2d__Text)hl_alloc_obj(&t$h2d_Text);
	r2 = r0->font;
	r3 = NULL;
	h2d_Text_new(r1,r2,r3);
	r0->tf = r1;
	r1 = r0->tf;
	if( r1 == NULL ) hl_null_access();
	r5 = (venum*)g$h2d_Align_Left;
	r5 = h2d_Text_set_textAlign(r1,r5);
	r3 = r0->spr;
	if( r3 == NULL ) hl_null_access();
	r1 = r0->tf;
	((void (*)(h2d__Object,h2d__Text))r3->$type->vobj_proto[1])(r3,r1);
	return;
}

ent__Player ent_Bullet_isPlayerHit(ent__Bullet r0) {
	h2d__col__Bounds r1, r4;
	Game r6;
	h2d__Object r2, r3;
	double r7, r8;
	ent__Player r5;
	r2 = ent_Actor_getSprite(((ent__Actor)r0));
	if( r2 == NULL ) hl_null_access();
	r3 = NULL;
	r1 = NULL;
	r1 = h2d_Object_getBounds(r2,r3,r1);
	r6 = r0->game;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->player;
	if( r5 == NULL ) hl_null_access();
	r2 = ent_Actor_getSprite(((ent__Actor)r5));
	if( r2 == NULL ) hl_null_access();
	r3 = NULL;
	r4 = NULL;
	r4 = h2d_Object_getBounds(r2,r3,r4);
	if( r1 == NULL ) hl_null_access();
	r7 = r1->xMin;
	if( r4 == NULL ) hl_null_access();
	r8 = r4->xMax;
	if( r8 < r7 ) goto label$4e6e752_2_32;
	r7 = r1->yMin;
	r8 = r4->yMax;
	if( r8 < r7 ) goto label$4e6e752_2_32;
	r7 = r1->xMax;
	r8 = r4->xMin;
	if( r7 < r8 ) goto label$4e6e752_2_32;
	r7 = r1->yMax;
	r8 = r4->yMin;
	if( r7 < r8 ) goto label$4e6e752_2_32;
	r6 = r0->game;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->player;
	return r5;
	label$4e6e752_2_32:
	r5 = NULL;
	return r5;
}

ent__Invader ent_Bullet_isHit(ent__Bullet r0) {
	h2d__col__Bounds r9, r12;
	Game r3;
	hl__types__ArrayObj r2;
	h2d__Object r10, r11;
	double r13, r14;
	vdynamic *r6;
	ent__Invader r5, r8;
	varray *r7;
	int r1, r4;
	r1 = 0;
	r3 = r0->game;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->activeInvaders;
	label$4e6e752_3_4:
	if( r2 == NULL ) hl_null_access();
	r4 = r2->length;
	if( r1 >= r4 ) goto label$4e6e752_3_48;
	r4 = r2->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$4e6e752_3_12;
	r5 = NULL;
	goto label$4e6e752_3_18;
	label$4e6e752_3_12:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r1];
	r5 = (ent__Invader)r6;
	r8 = (ent__Invader)hl_dyn_castp(&r6,&t$_dyn,&t$ent_Invader);
	if( r5 == r8 ) goto label$4e6e752_3_18;
	hl_assert();
	label$4e6e752_3_18:
	++r1;
	if( r5 ) goto label$4e6e752_3_21;
	goto label$4e6e752_3_4;
	label$4e6e752_3_21:
	r10 = ent_Actor_getSprite(((ent__Actor)r0));
	if( r10 == NULL ) hl_null_access();
	r11 = NULL;
	r9 = NULL;
	r9 = h2d_Object_getBounds(r10,r11,r9);
	if( r5 == NULL ) hl_null_access();
	r10 = ent_Actor_getSprite(((ent__Actor)r5));
	if( r10 == NULL ) hl_null_access();
	r11 = NULL;
	r12 = NULL;
	r12 = h2d_Object_getBounds(r10,r11,r12);
	if( r9 == NULL ) hl_null_access();
	r13 = r9->xMin;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->xMax;
	if( r14 < r13 ) goto label$4e6e752_3_47;
	r13 = r9->yMin;
	r14 = r12->yMax;
	if( r14 < r13 ) goto label$4e6e752_3_47;
	r13 = r9->xMax;
	r14 = r12->xMin;
	if( r13 < r14 ) goto label$4e6e752_3_47;
	r13 = r9->yMax;
	r14 = r12->yMin;
	if( r13 < r14 ) goto label$4e6e752_3_47;
	return r5;
	label$4e6e752_3_47:
	goto label$4e6e752_3_4;
	label$4e6e752_3_48:
	r5 = NULL;
	return r5;
}

void ent_Bullet_destroy(ent__Bullet r0) {
	bool r1;
	r1 = true;
	r0->gone = r1;
	ent_Actor_destroy(((ent__Actor)r0));
	return;
}

void ent_Bullet_update(ent__Bullet r0,double r1) {
	Game r12;
	bool r3;
	ent__Wall r9;
	ui__Score r11;
	ent__$Bullet r8;
	ent__Player r13;
	double r4, r5;
	h2d__Scene r14;
	ent__Invader r10;
	int r6, r7;
	r3 = r0->gone;
	if( r3 ) goto label$4e6e752_5_36;
	r4 = r0->y;
	r6 = r0->dir;
	r8 = (ent__$Bullet)g$_ent_Bullet;
	r7 = r8->SPEED;
	r6 = r6 * r7;
	r5 = (double)r6;
	r5 = r5 * r1;
	r4 = r4 + r5;
	r0->y = r4;
	r9 = ent_Actor_isWallHit(((ent__Actor)r0));
	if( !r9 ) goto label$4e6e752_5_17;
	if( r9 == NULL ) hl_null_access();
	ent_Wall_damage(r9);
	ent_Bullet_destroy(r0);
	goto label$4e6e752_5_36;
	label$4e6e752_5_17:
	r3 = r0->enemy;
	if( !r3 ) goto label$4e6e752_5_31;
	r10 = ent_Bullet_isHit(r0);
	if( !r10 ) goto label$4e6e752_5_30;
	r12 = r0->game;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->gameScore;
	if( r11 == NULL ) hl_null_access();
	r6 = 10;
	ui_Score_addScore(r11,r6);
	if( r10 == NULL ) hl_null_access();
	ent_Invader_destroy(r10);
	ent_Bullet_destroy(r0);
	label$4e6e752_5_30:
	goto label$4e6e752_5_36;
	label$4e6e752_5_31:
	r13 = ent_Bullet_isPlayerHit(r0);
	if( !r13 ) goto label$4e6e752_5_36;
	if( r13 == NULL ) hl_null_access();
	ent_Player_destroy(r13);
	ent_Bullet_destroy(r0);
	label$4e6e752_5_36:
	r4 = r0->y;
	r5 = 0.;
	if( r5 >= r4 ) goto label$4e6e752_5_47;
	r4 = r0->y;
	r12 = r0->game;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->scene;
	if( r14 == NULL ) hl_null_access();
	r6 = r14->height;
	r5 = (double)r6;
	if( !(r4 >= r5) ) goto label$4e6e752_5_50;
	label$4e6e752_5_47:
	r3 = true;
	r0->gone = r3;
	ent_Bullet_destroy(r0);
	label$4e6e752_5_50:
	r4 = r0->timer;
	r5 = r0->timeOut;
	if( !(r5 >= r4) ) goto label$4e6e752_5_57;
	r4 = r0->timer;
	r4 = r4 + r1;
	r0->timer = r4;
	goto label$4e6e752_5_59;
	label$4e6e752_5_57:
	r4 = 0.;
	r0->timer = r4;
	label$4e6e752_5_59:
	ent_Actor_update(((ent__Actor)r0),r1);
	return;
}

void ent_Bullet_new(ent__Bullet r0,double r1,double r2,int r3,bool r4,h2d__Tile r5) {
	bool r8;
	h2d__Object r17;
	h2d__Font r6;
	h2d__Bitmap r16;
	double r7, r12, r14;
	double *r11, *r13, *r15;
	int r9;
	r6 = hxd_res_DefaultFont_get();
	r0->font = r6;
	r7 = 0.5;
	r0->timeOut = r7;
	r7 = 0.;
	r0->timer = r7;
	r8 = false;
	r0->gone = r8;
	r8 = true;
	r0->enemy = r8;
	r9 = 0;
	r0->dir = r9;
	r7 = r1;
	r11 = &r7;
	r12 = r2;
	r13 = &r12;
	r9 = 6;
	r14 = (double)r9;
	r15 = &r14;
	ent_Actor_new(((ent__Actor)r0),r11,r13,r15);
	r0->dir = r3;
	r0->enemy = r4;
	r16 = (h2d__Bitmap)hl_alloc_obj(&t$h2d_Bitmap);
	r17 = r0->spr;
	h2d_Bitmap_new(r16,r5,r17);
	r0->bullet = r16;
	ent_Bullet_init(r0);
	return;
}

