// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ent/Entity.h>
#include <h2d/Tile.h>
void ent_Actor_new(ent__Actor,double*,double*,double*);
extern hl_type t$h2d_Anim;
extern hl_type t$h2d_Tile;
#include <hl/natives.h>
extern hl_type t$_dyn;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$_f64;
void h2d_Anim_new(h2d__Anim,hl__types__ArrayObj,vdynamic*,h2d__Object);

void ent_Entity_new(ent__Entity r0,hl__types__ArrayObj r1,double r2,double r3,double r4,bool* r5) {
	hl__types__ArrayObj r14;
	hl_type *r17;
	h2d__Anim r15;
	bool r6;
	h2d__Object r26;
	h2d__Tile r20, r23;
	double r8, r10, r12, r24;
	vdynamic *r21, *r25;
	double *r9, *r11, *r13;
	int r18, r19;
	varray *r16, *r22;
	if( r5 ) goto label$fa72080_1_3;
	r6 = true;
	goto label$fa72080_1_4;
	label$fa72080_1_3:
	r6 = *r5;
	label$fa72080_1_4:
	r8 = r2;
	r9 = &r8;
	r10 = r3;
	r11 = &r10;
	r12 = r4;
	r13 = &r12;
	ent_Actor_new(((ent__Actor)r0),r9,r11,r13);
	r0->frames = r1;
	if( !r6 ) goto label$fa72080_1_51;
	r15 = (h2d__Anim)hl_alloc_obj(&t$h2d_Anim);
	r17 = &t$h2d_Tile;
	r18 = 2;
	r16 = hl_alloc_array(r17,r18);
	if( r1 == NULL ) hl_null_access();
	r18 = 0;
	r19 = r1->length;
	if( ((unsigned)r18) < ((unsigned)r19) ) goto label$fa72080_1_23;
	r20 = NULL;
	goto label$fa72080_1_29;
	label$fa72080_1_23:
	r22 = r1->array;
	r21 = ((vdynamic**)(r22 + 1))[r18];
	r20 = (h2d__Tile)r21;
	r23 = (h2d__Tile)hl_dyn_castp(&r21,&t$_dyn,&t$h2d_Tile);
	if( r20 == r23 ) goto label$fa72080_1_29;
	hl_assert();
	label$fa72080_1_29:
	r18 = 0;
	((h2d__Tile*)(r16 + 1))[r18] = r20;
	r18 = 1;
	r19 = r1->length;
	if( ((unsigned)r18) < ((unsigned)r19) ) goto label$fa72080_1_36;
	r20 = NULL;
	goto label$fa72080_1_42;
	label$fa72080_1_36:
	r22 = r1->array;
	r21 = ((vdynamic**)(r22 + 1))[r18];
	r20 = (h2d__Tile)r21;
	r23 = (h2d__Tile)hl_dyn_castp(&r21,&t$_dyn,&t$h2d_Tile);
	if( r20 == r23 ) goto label$fa72080_1_42;
	hl_assert();
	label$fa72080_1_42:
	r18 = 1;
	((h2d__Tile*)(r16 + 1))[r18] = r20;
	r14 = hl_types_ArrayObj_alloc(r16);
	r18 = 2;
	r24 = (double)r18;
	r25 = hl_alloc_dynamic(&t$_f64);
	r25->v.d = r24;
	r26 = r0->spr;
	h2d_Anim_new(r15,r14,r25,r26);
	r0->anim = r15;
	label$fa72080_1_51:
	((void (*)(ent__Entity))r0->$type->vobj_proto[0])(r0);
	return;
}

