// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ent/Invader.h>
bool h2d_Object_set_visible(h2d__Object,bool);
extern ent__$Invader g$_ent_Invader;
#include <h2d/col/Bounds.h>
#include <h2d/Scene.h>
h2d__col__Bounds h2d_Object_getSize(h2d__Object,h2d__col__Bounds);
#include <h2d/Tile.h>
extern hl_type t$h2d_Anim;
extern hl_type t$h2d_Tile;
#include <hl/natives.h>
extern hl_type t$_dyn;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$_f64;
void h2d_Anim_new(h2d__Anim,hl__types__ArrayObj,vdynamic*,h2d__Object);
#include <_std/Win.h>
void ent_Actor_destroy(ent__Actor);
extern hl_type t$hl_types_ArrayObj;
bool hl_types_ArrayObj_contains(hl__types__ArrayObj,vdynamic*);
int hl_types_ArrayObj_indexOf(hl__types__ArrayObj,vdynamic*,vdynamic*);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
extern hl_type t$ent_Invader;
extern hl_type t$Win;
void Win_new(Win);
void Win_youWin(Win);
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log g$_haxe_Log;
extern hl_type t$_i32;
extern hl_type t$vrt_329ffa8;
extern String s$src_ent_Invader_hx;
extern hl_type t$String;
extern String s$ent_Invader;
extern String s$downLogic;
extern hl_type t$vrt_eaa6a3b;
#include <ent/Player.h>
h2d__Object ent_Actor_getSprite(ent__Actor);
h2d__col__Bounds h2d_Object_getBounds(h2d__Object,h2d__Object,h2d__col__Bounds);
#include <ent/Wall.h>
ent__Wall ent_Actor_isWallHit(ent__Actor);
void ent_Player_destroy(ent__Player);
void ent_Actor_update(ent__Actor,double);
void ent_Entity_new(ent__Entity,hl__types__ArrayObj,double,double,double,bool*);

void ent_Invader_moveTo(ent__Invader r0,int r1,double r2) {
	h2d__Anim r4;
	bool r6;
	ent__$Invader r9;
	double r7, r8, r10;
	int r5;
	r4 = r0->extraAnim;
	if( !r4 ) goto label$571b1df_1_21;
	r5 = -1;
	if( r1 != r5 ) goto label$571b1df_1_13;
	r4 = r0->extraAnim;
	if( r4 == NULL ) hl_null_access();
	r6 = true;
	r6 = h2d_Object_set_visible(((h2d__Object)r4),r6);
	r4 = r0->anim;
	if( r4 == NULL ) hl_null_access();
	r6 = false;
	r6 = h2d_Object_set_visible(((h2d__Object)r4),r6);
	goto label$571b1df_1_21;
	label$571b1df_1_13:
	r4 = r0->anim;
	if( r4 == NULL ) hl_null_access();
	r6 = true;
	r6 = h2d_Object_set_visible(((h2d__Object)r4),r6);
	r4 = r0->extraAnim;
	if( r4 == NULL ) hl_null_access();
	r6 = false;
	r6 = h2d_Object_set_visible(((h2d__Object)r4),r6);
	label$571b1df_1_21:
	r7 = r0->x;
	r9 = (ent__$Invader)g$_ent_Invader;
	r8 = r9->SPEED;
	r10 = r0->multiplier;
	r8 = r8 * r10;
	r8 = r8 * r2;
	r10 = (double)r1;
	r8 = r8 * r10;
	r7 = r7 + r8;
	r0->x = r7;
	return;
}

bool ent_Invader_isAtEdge(ent__Invader r0) {
	h2d__col__Bounds r4, r7;
	Game r11;
	bool r3;
	h2d__Object r5;
	double r1, r2, r6, r8;
	h2d__Scene r10;
	int r9;
	r1 = r0->x;
	r2 = 0.;
	if( !(r1 < r2) ) goto label$571b1df_2_7;
	r1 = 0.;
	r0->x = r1;
	r3 = true;
	return r3;
	label$571b1df_2_7:
	r1 = r0->x;
	r5 = r0->spr;
	if( r5 == NULL ) hl_null_access();
	r4 = NULL;
	r4 = h2d_Object_getSize(r5,r4);
	if( r4 == NULL ) hl_null_access();
	r6 = r4->xMax;
	r8 = r4->xMin;
	r6 = r6 - r8;
	r2 = r1 + r6;
	r11 = r0->game;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->scene;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->width;
	r6 = (double)r9;
	if( !(r6 < r2) ) goto label$571b1df_2_42;
	r11 = r0->game;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->scene;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->width;
	r5 = r0->spr;
	if( r5 == NULL ) hl_null_access();
	r7 = NULL;
	r7 = h2d_Object_getSize(r5,r7);
	r2 = (double)r9;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->xMax;
	r8 = r7->xMin;
	r6 = r6 - r8;
	r2 = r2 - r6;
	r0->x = r2;
	r3 = true;
	return r3;
	label$571b1df_2_42:
	r3 = false;
	return r3;
}

void ent_Invader_init(ent__Invader r0) {
	hl__types__ArrayObj r3;
	hl_type *r7;
	h2d__Anim r5;
	bool r15;
	h2d__Object r14;
	h2d__Tile r8, r11;
	double r12;
	vdynamic *r9, *r13;
	varray *r6, *r10;
	int r2, r4;
	r3 = r0->frames;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r4 = 3;
	if( r2 != r4 ) goto label$571b1df_3_50;
	r5 = (h2d__Anim)hl_alloc_obj(&t$h2d_Anim);
	r7 = &t$h2d_Tile;
	r2 = 2;
	r6 = hl_alloc_array(r7,r2);
	r3 = r0->frames;
	if( r3 == NULL ) hl_null_access();
	r2 = 0;
	r4 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r4) ) goto label$571b1df_3_16;
	r8 = NULL;
	goto label$571b1df_3_22;
	label$571b1df_3_16:
	r10 = r3->array;
	r9 = ((vdynamic**)(r10 + 1))[r2];
	r8 = (h2d__Tile)r9;
	r11 = (h2d__Tile)hl_dyn_castp(&r9,&t$_dyn,&t$h2d_Tile);
	if( r8 == r11 ) goto label$571b1df_3_22;
	hl_assert();
	label$571b1df_3_22:
	r2 = 0;
	((h2d__Tile*)(r6 + 1))[r2] = r8;
	r3 = r0->frames;
	if( r3 == NULL ) hl_null_access();
	r2 = 2;
	r4 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r4) ) goto label$571b1df_3_31;
	r8 = NULL;
	goto label$571b1df_3_37;
	label$571b1df_3_31:
	r10 = r3->array;
	r9 = ((vdynamic**)(r10 + 1))[r2];
	r8 = (h2d__Tile)r9;
	r11 = (h2d__Tile)hl_dyn_castp(&r9,&t$_dyn,&t$h2d_Tile);
	if( r8 == r11 ) goto label$571b1df_3_37;
	hl_assert();
	label$571b1df_3_37:
	r2 = 1;
	((h2d__Tile*)(r6 + 1))[r2] = r8;
	r3 = hl_types_ArrayObj_alloc(r6);
	r2 = 2;
	r12 = (double)r2;
	r13 = hl_alloc_dynamic(&t$_f64);
	r13->v.d = r12;
	r14 = r0->spr;
	h2d_Anim_new(r5,r3,r13,r14);
	r0->extraAnim = r5;
	r5 = r0->extraAnim;
	if( r5 == NULL ) hl_null_access();
	r15 = false;
	r15 = h2d_Object_set_visible(((h2d__Object)r5),r15);
	label$571b1df_3_50:
	return;
}

void ent_Invader_destroy(ent__Invader r0) {
	Game r4;
	hl__types__ArrayObj r3, r10, r14;
	bool r9;
	ent__Invader r12, r15;
	vdynamic *r7, *r11;
	Win r17;
	varray *r8;
	int r2, r5, r6, r13, r16;
	ent_Actor_destroy(((ent__Actor)r0));
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->invaders;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r5 = 1;
	r2 = r2 - r5;
	label$571b1df_4_8:
	r6 = 0;
	if( r2 < r6 ) goto label$571b1df_4_104;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->invaders;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r6) ) goto label$571b1df_4_19;
	r3 = NULL;
	goto label$571b1df_4_22;
	label$571b1df_4_19:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r2];
	r3 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
	label$571b1df_4_22:
	if( r3 == NULL ) hl_null_access();
	r9 = hl_types_ArrayObj_contains(r3,((vdynamic*)r0));
	if( !r9 ) goto label$571b1df_4_102;
	r11 = NULL;
	r5 = hl_types_ArrayObj_indexOf(r3,((vdynamic*)r0),r11);
	r12 = NULL;
	r13 = r3->length;
	if( ((unsigned)r5) < ((unsigned)r13) ) goto label$571b1df_4_31;
	hl_types_ArrayObj___expand(r3,r5);
	label$571b1df_4_31:
	r8 = r3->array;
	((ent__Invader*)(r8 + 1))[r5] = r12;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r6 = r4->aliens;
	--r6;
	r4->aliens = r6;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r10 = r4->activeInvaders;
	if( r10 == NULL ) hl_null_access();
	r9 = hl_types_ArrayObj_contains(r10,((vdynamic*)r0));
	if( !r9 ) goto label$571b1df_4_102;
	r13 = 0;
	if( r2 != r13 ) goto label$571b1df_4_48;
	r10 = r3;
	goto label$571b1df_4_61;
	label$571b1df_4_48:
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r10 = r4->invaders;
	if( r10 == NULL ) hl_null_access();
	r13 = 1;
	r6 = r2 - r13;
	r13 = r10->length;
	if( ((unsigned)r6) < ((unsigned)r13) ) goto label$571b1df_4_58;
	r10 = NULL;
	goto label$571b1df_4_61;
	label$571b1df_4_58:
	r8 = r10->array;
	r7 = ((vdynamic**)(r8 + 1))[r6];
	r10 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
	label$571b1df_4_61:
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r14 = r4->activeInvaders;
	if( r14 == NULL ) hl_null_access();
	r12 = NULL;
	r13 = r14->length;
	if( ((unsigned)r5) < ((unsigned)r13) ) goto label$571b1df_4_69;
	hl_types_ArrayObj___expand(r14,r5);
	label$571b1df_4_69:
	r8 = r14->array;
	((ent__Invader*)(r8 + 1))[r5] = r12;
	if( r10 == NULL ) hl_null_access();
	r13 = r10->length;
	if( ((unsigned)r5) < ((unsigned)r13) ) goto label$571b1df_4_76;
	r12 = NULL;
	goto label$571b1df_4_82;
	label$571b1df_4_76:
	r8 = r10->array;
	r7 = ((vdynamic**)(r8 + 1))[r5];
	r12 = (ent__Invader)r7;
	r15 = (ent__Invader)hl_dyn_castp(&r7,&t$_dyn,&t$ent_Invader);
	if( r12 == r15 ) goto label$571b1df_4_82;
	hl_assert();
	label$571b1df_4_82:
	if( !r12 ) goto label$571b1df_4_102;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r14 = r4->activeInvaders;
	if( r14 == NULL ) hl_null_access();
	r16 = r10->length;
	if( ((unsigned)r5) < ((unsigned)r16) ) goto label$571b1df_4_91;
	r12 = NULL;
	goto label$571b1df_4_97;
	label$571b1df_4_91:
	r8 = r10->array;
	r7 = ((vdynamic**)(r8 + 1))[r5];
	r12 = (ent__Invader)r7;
	r15 = (ent__Invader)hl_dyn_castp(&r7,&t$_dyn,&t$ent_Invader);
	if( r12 == r15 ) goto label$571b1df_4_97;
	hl_assert();
	label$571b1df_4_97:
	r13 = r14->length;
	if( ((unsigned)r5) < ((unsigned)r13) ) goto label$571b1df_4_100;
	hl_types_ArrayObj___expand(r14,r5);
	label$571b1df_4_100:
	r8 = r14->array;
	((ent__Invader*)(r8 + 1))[r5] = r12;
	label$571b1df_4_102:
	--r2;
	goto label$571b1df_4_8;
	label$571b1df_4_104:
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->aliens;
	r6 = 0;
	if( r6 < r5 ) goto label$571b1df_4_112;
	r17 = (Win)hl_alloc_obj(&t$Win);
	Win_new(r17);
	Win_youWin(r17);
	label$571b1df_4_112:
	return;
}

void ent_Invader_moveDown(ent__Invader r0,double r1) {
	h2d__col__Bounds r6;
	h2d__Anim r10;
	bool r2;
	h2d__Object r7;
	double r3, r4, r8, r9;
	r2 = r0->movingRight;
	r2 = !r2;
	r0->movingRight = r2;
	r3 = r0->multiplier;
	r4 = 1.199999999999999956;
	r3 = r3 * r4;
	r0->multiplier = r3;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->y;
	r7 = r0->spr;
	if( r7 == NULL ) hl_null_access();
	r6 = NULL;
	r6 = h2d_Object_getSize(r7,r6);
	if( r6 == NULL ) hl_null_access();
	r8 = r6->yMax;
	r9 = r6->yMin;
	r8 = r8 - r9;
	r9 = 2.;
	r8 = r8 / r9;
	r9 = 0.5999999999999999778;
	r8 = r8 * r9;
	r4 = r3 + r8;
	r0->y = r4;
	r10 = r0->anim;
	if( r10 == NULL ) hl_null_access();
	r4 = r10->speed;
	r8 = r0->multiplier;
	r9 = 10.;
	r8 = r8 / r9;
	r4 = r4 + r8;
	r10->speed = r4;
	r10 = r0->extraAnim;
	if( !r10 ) goto label$571b1df_5_41;
	r10 = r0->extraAnim;
	if( r10 == NULL ) hl_null_access();
	r4 = r10->speed;
	r8 = r0->multiplier;
	r9 = 10.;
	r8 = r8 / r9;
	r4 = r4 + r8;
	r10->speed = r4;
	label$571b1df_5_41:
	return;
}

void ent_Invader_downLogic(ent__Invader r0) {
	String r11;
	vvirtual *r10, *r12;
	hl__types__ArrayObj r8;
	Game r1;
	bool r13;
	haxe__$Log r6;
	vclosure *r5;
	double r2, r3;
	vdynamic *r9;
	int r7;
	r1 = r0->game;
	if( r1 == NULL ) hl_null_access();
	r2 = r1->shootTimeoutMax;
	r3 = 2.;
	r2 = r2 - r3;
	r1->shootTimeoutMax = r2;
	r6 = (haxe__$Log)g$_haxe_Log;
	r5 = r6->trace;
	if( r5 == NULL ) hl_null_access();
	r1 = r0->game;
	if( r1 == NULL ) hl_null_access();
	r8 = r1->activeInvaders;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->length;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r7;
	r10 = hl_alloc_virtual(&t$vrt_329ffa8);
	r11 = (String)s$src_ent_Invader_hx;
	if( hl_vfields(r10)[1] ) *(String*)(hl_vfields(r10)[1]) = (String)r11; else hl_dyn_setp(r10->value,37969014/*fileName*/,&t$String,r11);
	r7 = 85;
	if( hl_vfields(r10)[2] ) *(int*)(hl_vfields(r10)[2]) = (int)r7; else hl_dyn_seti(r10->value,371360620/*lineNumber*/,&t$_i32,r7);
	r11 = (String)s$ent_Invader;
	if( hl_vfields(r10)[0] ) *(String*)(hl_vfields(r10)[0]) = (String)r11; else hl_dyn_setp(r10->value,-63073762/*className*/,&t$String,r11);
	r11 = (String)s$downLogic;
	if( hl_vfields(r10)[3] ) *(String*)(hl_vfields(r10)[3]) = (String)r11; else hl_dyn_setp(r10->value,302979532/*methodName*/,&t$String,r11);
	r12 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r10);
	r5->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r5->fun)((vdynamic*)r5->value,r9,r12) : ((void (*)(vdynamic*,vvirtual*))r5->fun)(r9,r12);
	r13 = true;
	r0->called = r13;
	return;
}

bool ent_Invader_isPlayerHit(ent__Invader r0) {
	h2d__col__Bounds r1, r4;
	Game r6;
	bool r7;
	h2d__Object r2, r3;
	double r8, r9;
	ent__Player r5;
	r2 = ent_Actor_getSprite(((ent__Actor)r0));
	if( r2 == NULL ) hl_null_access();
	r3 = NULL;
	r1 = NULL;
	r1 = h2d_Object_getBounds(r2,r3,r1);
	r6 = r0->game;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->player;
	if( r5 == NULL ) hl_null_access();
	r2 = ent_Actor_getSprite(((ent__Actor)r5));
	if( r2 == NULL ) hl_null_access();
	r3 = NULL;
	r4 = NULL;
	r4 = h2d_Object_getBounds(r2,r3,r4);
	if( r1 == NULL ) hl_null_access();
	r8 = r1->xMin;
	if( r4 == NULL ) hl_null_access();
	r9 = r4->xMax;
	if( r9 < r8 ) goto label$571b1df_7_30;
	r8 = r1->yMin;
	r9 = r4->yMax;
	if( r9 < r8 ) goto label$571b1df_7_30;
	r8 = r1->xMax;
	r9 = r4->xMin;
	if( r8 < r9 ) goto label$571b1df_7_30;
	r8 = r1->yMax;
	r9 = r4->yMin;
	if( r8 < r9 ) goto label$571b1df_7_30;
	r7 = false;
	goto label$571b1df_7_31;
	label$571b1df_7_30:
	r7 = true;
	label$571b1df_7_31:
	r7 = !r7;
	return r7;
}

void ent_Invader_update(ent__Invader r0,double r1) {
	hl__types__ArrayObj r11, r14, r18;
	Game r10;
	h2d__Anim r4;
	bool r6;
	ent__Wall r8;
	ent__Player r9;
	double r3, r5;
	ent__Invader r19, r20, r21, r22;
	vdynamic *r15;
	varray *r16;
	int r7, r12, r13, r17;
	r4 = r0->anim;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->curFrame;
	r5 = 1.;
	if( !(r3 >= r5) ) goto label$571b1df_8_12;
	r6 = r0->movingRight;
	if( !r6 ) goto label$571b1df_8_10;
	r7 = 1;
	ent_Invader_moveTo(r0,r7,r1);
	goto label$571b1df_8_12;
	label$571b1df_8_10:
	r7 = -1;
	ent_Invader_moveTo(r0,r7,r1);
	label$571b1df_8_12:
	r6 = ent_Invader_isPlayerHit(r0);
	if( r6 ) goto label$571b1df_8_16;
	r8 = ent_Actor_isWallHit(((ent__Actor)r0));
	if( !r8 ) goto label$571b1df_8_27;
	label$571b1df_8_16:
	r10 = r0->game;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->player;
	if( r9 == NULL ) hl_null_access();
	r7 = 1;
	r9->lives = r7;
	r10 = r0->game;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->player;
	if( r9 == NULL ) hl_null_access();
	ent_Player_destroy(r9);
	label$571b1df_8_27:
	r6 = ent_Invader_isAtEdge(r0);
	if( !r6 ) goto label$571b1df_8_84;
	r7 = 0;
	r10 = r0->game;
	if( r10 == NULL ) hl_null_access();
	r11 = r10->invaders;
	label$571b1df_8_33:
	if( r11 == NULL ) hl_null_access();
	r13 = r11->length;
	if( r7 >= r13 ) goto label$571b1df_8_84;
	r13 = r11->length;
	if( ((unsigned)r7) < ((unsigned)r13) ) goto label$571b1df_8_41;
	r14 = NULL;
	goto label$571b1df_8_44;
	label$571b1df_8_41:
	r16 = r11->array;
	r15 = ((vdynamic**)(r16 + 1))[r7];
	r14 = (hl__types__ArrayObj)hl_dyn_castp(&r15,&t$_dyn,&t$hl_types_ArrayObj);
	label$571b1df_8_44:
	++r7;
	r12 = 0;
	label$571b1df_8_46:
	if( r14 == NULL ) hl_null_access();
	r17 = r14->length;
	if( r12 >= r17 ) goto label$571b1df_8_83;
	r17 = r14->length;
	if( ((unsigned)r12) < ((unsigned)r17) ) goto label$571b1df_8_54;
	r19 = NULL;
	goto label$571b1df_8_60;
	label$571b1df_8_54:
	r16 = r14->array;
	r15 = ((vdynamic**)(r16 + 1))[r12];
	r19 = (ent__Invader)r15;
	r20 = (ent__Invader)hl_dyn_castp(&r15,&t$_dyn,&t$ent_Invader);
	if( r19 == r20 ) goto label$571b1df_8_60;
	hl_assert();
	label$571b1df_8_60:
	++r12;
	r10 = r0->game;
	if( r10 == NULL ) hl_null_access();
	r18 = r10->activeInvaders;
	if( r18 == NULL ) hl_null_access();
	r13 = 0;
	r17 = r18->length;
	if( ((unsigned)r13) < ((unsigned)r17) ) goto label$571b1df_8_70;
	r21 = NULL;
	goto label$571b1df_8_76;
	label$571b1df_8_70:
	r16 = r18->array;
	r15 = ((vdynamic**)(r16 + 1))[r13];
	r21 = (ent__Invader)r15;
	r22 = (ent__Invader)hl_dyn_castp(&r15,&t$_dyn,&t$ent_Invader);
	if( r21 == r22 ) goto label$571b1df_8_76;
	hl_assert();
	label$571b1df_8_76:
	if( r19 != r21 ) goto label$571b1df_8_78;
	ent_Invader_downLogic(r0);
	label$571b1df_8_78:
	if( r19 ) goto label$571b1df_8_80;
	goto label$571b1df_8_46;
	label$571b1df_8_80:
	if( r19 == NULL ) hl_null_access();
	ent_Invader_moveDown(r19,r1);
	goto label$571b1df_8_46;
	label$571b1df_8_83:
	goto label$571b1df_8_33;
	label$571b1df_8_84:
	r4 = r0->anim;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->curFrame;
	r7 = (int)r3;
	r0->oldFrame = r7;
	ent_Actor_update(((ent__Actor)r0),r1);
	return;
}

void ent_Invader_new(ent__Invader r0,hl__types__ArrayObj r1,double r2,double r3,double r4,bool* r5) {
	bool r6, r8;
	double r7;
	int r9;
	if( r5 ) goto label$571b1df_9_3;
	r6 = true;
	goto label$571b1df_9_4;
	label$571b1df_9_3:
	r6 = *r5;
	label$571b1df_9_4:
	r7 = 1.;
	r0->multiplier = r7;
	r8 = false;
	r0->called = r8;
	r9 = 0;
	r0->oldFrame = r9;
	r8 = false;
	r0->played = r8;
	r8 = true;
	r0->movingRight = r8;
	r8 = r6;
	r5 = &r8;
	ent_Entity_new(((ent__Entity)r0),r1,r2,r3,r4,r5);
	return;
}

