// Generated by HLC 4.1.4 (HL v5)
#ifndef INC_ent__Invader
#define INC_ent__Invader
typedef struct _ent__$Invader *ent__$Invader;
typedef struct _ent__Invader *ent__Invader;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <ent/Entity.h>
#include <ent/Actor.h>
#include <_std/Game.h>
#include <h2d/Object.h>
#include <h2d/Anim.h>
#include <hl/types/ArrayObj.h>


struct _ent__$Invader {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	double SPEED;
};
struct _ent__Invader {
	hl_type *$type;
	Game game;
	double x;
	double y;
	double scale;
	h2d__Object spr;
	h2d__Anim anim;
	hl__types__ArrayObj frames;
	bool movingRight;
	bool played;
	int oldFrame;
	bool called;
	h2d__Anim extraAnim;
	double multiplier;
};
#endif

