// Generated by HLC 4.1.4 (HL v5)
#ifndef INC_ent__Player
#define INC_ent__Player
typedef struct _ent__$Player *ent__$Player;
typedef struct _ent__Player *ent__Player;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <ent/Entity.h>
#include <ent/Actor.h>
#include <_std/Game.h>
#include <h2d/Object.h>
#include <h2d/Anim.h>
#include <hl/types/ArrayObj.h>
#include <ent/Bullet.h>
#include <_std/GameOver.h>


struct _ent__$Player {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	int SPEED;
};
struct _ent__Player {
	hl_type *$type;
	Game game;
	double x;
	double y;
	double scale;
	h2d__Object spr;
	h2d__Anim anim;
	hl__types__ArrayObj frames;
	double delta;
	ent__Bullet bullet;
	int lives;
	bool gameOver;
	GameOver over;
};
#endif

