// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ent/Player.h>
extern hl_type t$GameOver;
void GameOver_new(GameOver);
void ent_Actor_destroy(ent__Actor);
void ent_Player_doGameOver(ent__Player,int);
#include <ui/Lives.h>
void ui_Lives_updateLives(ui__Lives);
void GameOver_gameOver(GameOver);
#include <h2d/col/Bounds.h>
#include <h2d/Tile.h>
#include <h2d/Scene.h>
bool hl_types_ArrayObj_contains(hl__types__ArrayObj,vdynamic*);
h2d__col__Bounds h2d_Object_getSize(h2d__Object,h2d__col__Bounds);
extern hl_type t$ent_Bullet;
void ent_Bullet_new(ent__Bullet,double,double,int,bool,h2d__Tile);
h2d__Object ent_Actor_getSprite(ent__Actor);
#include <h2d/Layers.h>
void h2d_Layers_addChild(h2d__Layers,h2d__Object);
extern ent__$Player g$_ent_Player;
double h2d_Anim_set_currentFrame(h2d__Anim,double);
bool hxd_Key_isDown(int);
bool hxd_Key_isPressed(int);
void ent_Actor_update(ent__Actor,double);
void ent_Entity_new(ent__Entity,hl__types__ArrayObj,double,double,double,bool*);

void ent_Player_init(ent__Player r0) {
	h2d__Anim r1;
	bool r2;
	GameOver r3;
	r1 = r0->anim;
	if( r1 == NULL ) hl_null_access();
	r2 = true;
	r1->pause = r2;
	r3 = (GameOver)hl_alloc_obj(&t$GameOver);
	GameOver_new(r3);
	r0->over = r3;
	return;
}

void ent_Player_destroy(ent__Player r0) {
	int r2, r3;
	ent_Actor_destroy(((ent__Actor)r0));
	r2 = r0->lives;
	r3 = 1;
	r2 = r2 - r3;
	r0->lives = r2;
	r2 = r0->lives;
	ent_Player_doGameOver(r0,r2);
	return;
}

void ent_Player_doGameOver(ent__Player r0,int r1) {
	Game r4;
	bool r6;
	ui__Lives r3;
	GameOver r5;
	r0->lives = r1;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->lives;
	if( r3 == NULL ) hl_null_access();
	ui_Lives_updateLives(r3);
	r5 = r0->over;
	if( r5 == NULL ) hl_null_access();
	GameOver_gameOver(r5);
	r6 = true;
	r0->gameOver = r6;
	return;
}

void ent_Player_shoot(ent__Player r0) {
	h2d__col__Bounds r7;
	Game r4;
	hl__types__ArrayObj r3;
	bool r2;
	h2d__Object r8;
	h2d__Tile r13;
	ent__Bullet r5;
	double r6, r9, r10, r11;
	h2d__Scene r14;
	int r12;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->entities;
	if( r3 == NULL ) hl_null_access();
	r5 = r0->bullet;
	r2 = hl_types_ArrayObj_contains(r3,((vdynamic*)r5));
	if( r2 ) goto label$df9cf7a_4_36;
	r6 = r0->x;
	r8 = r0->spr;
	if( r8 == NULL ) hl_null_access();
	r7 = NULL;
	r7 = h2d_Object_getSize(r8,r7);
	r5 = (ent__Bullet)hl_alloc_obj(&t$ent_Bullet);
	if( r7 == NULL ) hl_null_access();
	r10 = r7->xMax;
	r11 = r7->xMin;
	r10 = r10 - r11;
	r11 = 2.;
	r10 = r10 / r11;
	r9 = r6 + r10;
	r10 = r0->y;
	r12 = -1;
	r2 = true;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r13 = r4->bulletTile;
	ent_Bullet_new(r5,r9,r10,r12,r2,r13);
	r0->bullet = r5;
	r4 = r0->game;
	if( r4 == NULL ) hl_null_access();
	r14 = r4->scene;
	if( r14 == NULL ) hl_null_access();
	r5 = r0->bullet;
	if( r5 == NULL ) hl_null_access();
	r8 = ent_Actor_getSprite(((ent__Actor)r5));
	h2d_Layers_addChild(((h2d__Layers)r14),r8);
	label$df9cf7a_4_36:
	return;
}

void ent_Player_moveTo(ent__Player r0,int r1) {
	ent__$Player r5;
	h2d__Anim r7;
	double r2, r3, r6;
	int r4, r8;
	r2 = r0->x;
	r5 = (ent__$Player)g$_ent_Player;
	r4 = r5->SPEED;
	r3 = (double)r4;
	r6 = r0->delta;
	r3 = r3 * r6;
	r6 = (double)r1;
	r3 = r3 * r6;
	r2 = r2 + r3;
	r0->x = r2;
	r7 = r0->anim;
	if( r7 == NULL ) hl_null_access();
	r8 = 1;
	if( r1 != r8 ) goto label$df9cf7a_5_16;
	r2 = 0.;
	goto label$df9cf7a_5_17;
	label$df9cf7a_5_16:
	r2 = 1.;
	label$df9cf7a_5_17:
	r2 = h2d_Anim_set_currentFrame(r7,r2);
	return;
}

void ent_Player_update(ent__Player r0,double r1) {
	bool r3;
	int r4;
	r0->delta = r1;
	r3 = r0->gameOver;
	if( r3 ) goto label$df9cf7a_6_18;
	r4 = 39;
	r3 = hxd_Key_isDown(r4);
	if( !r3 ) goto label$df9cf7a_6_9;
	r4 = 1;
	ent_Player_moveTo(r0,r4);
	goto label$df9cf7a_6_14;
	label$df9cf7a_6_9:
	r4 = 37;
	r3 = hxd_Key_isDown(r4);
	if( !r3 ) goto label$df9cf7a_6_14;
	r4 = -1;
	ent_Player_moveTo(r0,r4);
	label$df9cf7a_6_14:
	r4 = 32;
	r3 = hxd_Key_isPressed(r4);
	if( !r3 ) goto label$df9cf7a_6_18;
	ent_Player_shoot(r0);
	label$df9cf7a_6_18:
	ent_Actor_update(((ent__Actor)r0),r1);
	return;
}

void ent_Player_new(ent__Player r0,hl__types__ArrayObj r1,double r2,double r3,double r4,bool* r5) {
	bool r6, r7;
	double r9;
	int r8;
	if( r5 ) goto label$df9cf7a_7_3;
	r6 = true;
	goto label$df9cf7a_7_4;
	label$df9cf7a_7_3:
	r6 = *r5;
	label$df9cf7a_7_4:
	r7 = false;
	r0->gameOver = r7;
	r8 = 3;
	r0->lives = r8;
	r9 = 0.;
	r0->delta = r9;
	r7 = r6;
	r5 = &r7;
	ent_Entity_new(((ent__Entity)r0),r1,r2,r3,r4,r5);
	return;
}

