// Generated by HLC 4.1.4 (HL v5)
#ifndef INC_ent__Wall
#define INC_ent__Wall
typedef struct _ent__$Wall *ent__$Wall;
typedef struct _ent__Wall *ent__Wall;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <ent/Actor.h>
#include <_std/Game.h>
#include <h2d/Object.h>
#include <h2d/Tile.h>
#include <h2d/Bitmap.h>


struct _ent__$Wall {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _ent__Wall {
	hl_type *$type;
	Game game;
	double x;
	double y;
	double scale;
	h2d__Object spr;
	h2d__Tile tile;
	h2d__Bitmap bmp;
	int health;
};
#endif

