// Generated by HLC 4.1.4 (HL v5)
#define HLC_BOOT
#include <hlc.h>
#include <ent/Wall.h>
#include <hl/types/ArrayObj.h>
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);
void ent_Actor_destroy(ent__Actor);
extern hl_type t$hl_types_ArrayObj;
extern hl_type t$_dyn;
extern hl_type t$h2d_Tile;
h2d__Tile h2d_Bitmap_set_tile(h2d__Bitmap,h2d__Tile);
#include <h2d/Scene.h>
void ent_Actor_new(ent__Actor,double*,double*,double*);
extern hl_type t$h2d_Bitmap;
void h2d_Bitmap_new(h2d__Bitmap,h2d__Tile,h2d__Object);
#include <h2d/Layers.h>
void h2d_Layers_addChild(h2d__Layers,h2d__Object);

void ent_Wall_damage(ent__Wall r0) {
	Game r6;
	hl__types__ArrayObj r5;
	bool r4;
	h2d__Tile r9, r10;
	h2d__Bitmap r11;
	vdynamic *r7;
	varray *r8;
	int r1, r2;
	r1 = r0->health;
	r2 = 1;
	r1 = r1 - r2;
	r0->health = r1;
	r1 = r0->health;
	r2 = 0;
	if( r2 < r1 ) goto label$166ddd8_1_14;
	r6 = r0->game;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->walls;
	if( r5 == NULL ) hl_null_access();
	r4 = hl_types_ArrayObj_remove(r5,((vdynamic*)r0));
	ent_Actor_destroy(((ent__Actor)r0));
	goto label$166ddd8_1_98;
	label$166ddd8_1_14:
	r1 = r0->health;
	switch(r1) {
		default:
		case 0:
			goto label$166ddd8_1_94;
		case 1:
			r6 = r0->game;
			if( r6 == NULL ) hl_null_access();
			r5 = r6->wallSprites;
			if( r5 == NULL ) hl_null_access();
			r1 = 1;
			r2 = r5->length;
			if( ((unsigned)r1) < ((unsigned)r2) ) goto label$166ddd8_1_26;
			r5 = NULL;
			goto label$166ddd8_1_29;
			label$166ddd8_1_26:
			r8 = r5->array;
			r7 = ((vdynamic**)(r8 + 1))[r1];
			r5 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
			label$166ddd8_1_29:
			if( r5 == NULL ) hl_null_access();
			r1 = 0;
			r2 = r5->length;
			if( ((unsigned)r1) < ((unsigned)r2) ) goto label$166ddd8_1_35;
			r9 = NULL;
			goto label$166ddd8_1_41;
			label$166ddd8_1_35:
			r8 = r5->array;
			r7 = ((vdynamic**)(r8 + 1))[r1];
			r9 = (h2d__Tile)r7;
			r10 = (h2d__Tile)hl_dyn_castp(&r7,&t$_dyn,&t$h2d_Tile);
			if( r9 == r10 ) goto label$166ddd8_1_41;
			hl_assert();
			label$166ddd8_1_41:
			r0->tile = r9;
			goto label$166ddd8_1_94;
		case 2:
			r6 = r0->game;
			if( r6 == NULL ) hl_null_access();
			r5 = r6->wallSprites;
			if( r5 == NULL ) hl_null_access();
			r1 = 1;
			r2 = r5->length;
			if( ((unsigned)r1) < ((unsigned)r2) ) goto label$166ddd8_1_52;
			r5 = NULL;
			goto label$166ddd8_1_55;
			label$166ddd8_1_52:
			r8 = r5->array;
			r7 = ((vdynamic**)(r8 + 1))[r1];
			r5 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
			label$166ddd8_1_55:
			if( r5 == NULL ) hl_null_access();
			r1 = 1;
			r2 = r5->length;
			if( ((unsigned)r1) < ((unsigned)r2) ) goto label$166ddd8_1_61;
			r9 = NULL;
			goto label$166ddd8_1_67;
			label$166ddd8_1_61:
			r8 = r5->array;
			r7 = ((vdynamic**)(r8 + 1))[r1];
			r9 = (h2d__Tile)r7;
			r10 = (h2d__Tile)hl_dyn_castp(&r7,&t$_dyn,&t$h2d_Tile);
			if( r9 == r10 ) goto label$166ddd8_1_67;
			hl_assert();
			label$166ddd8_1_67:
			r0->tile = r9;
			goto label$166ddd8_1_94;
		case 3:
			r6 = r0->game;
			if( r6 == NULL ) hl_null_access();
			r5 = r6->wallSprites;
			if( r5 == NULL ) hl_null_access();
			r1 = 0;
			r2 = r5->length;
			if( ((unsigned)r1) < ((unsigned)r2) ) goto label$166ddd8_1_78;
			r5 = NULL;
			goto label$166ddd8_1_81;
			label$166ddd8_1_78:
			r8 = r5->array;
			r7 = ((vdynamic**)(r8 + 1))[r1];
			r5 = (hl__types__ArrayObj)hl_dyn_castp(&r7,&t$_dyn,&t$hl_types_ArrayObj);
			label$166ddd8_1_81:
			if( r5 == NULL ) hl_null_access();
			r1 = 1;
			r2 = r5->length;
			if( ((unsigned)r1) < ((unsigned)r2) ) goto label$166ddd8_1_87;
			r9 = NULL;
			goto label$166ddd8_1_93;
			label$166ddd8_1_87:
			r8 = r5->array;
			r7 = ((vdynamic**)(r8 + 1))[r1];
			r9 = (h2d__Tile)r7;
			r10 = (h2d__Tile)hl_dyn_castp(&r7,&t$_dyn,&t$h2d_Tile);
			if( r9 == r10 ) goto label$166ddd8_1_93;
			hl_assert();
			label$166ddd8_1_93:
			r0->tile = r9;
	}
	label$166ddd8_1_94:
	r11 = r0->bmp;
	if( r11 == NULL ) hl_null_access();
	r9 = r0->tile;
	r9 = h2d_Bitmap_set_tile(r11,r9);
	label$166ddd8_1_98:
	return;
}

void ent_Wall_new(ent__Wall r0,double r1,double r2) {
	Game r12;
	hl__types__ArrayObj r11;
	h2d__Object r19;
	h2d__Tile r16, r17;
	h2d__Bitmap r18;
	double r5, r7, r9;
	h2d__Scene r20;
	vdynamic *r14;
	double *r6, *r8, *r10;
	varray *r15;
	int r3, r13;
	r3 = 4;
	r0->health = r3;
	r5 = r1;
	r6 = &r5;
	r7 = r2;
	r8 = &r7;
	r3 = 8;
	r9 = (double)r3;
	r10 = &r9;
	ent_Actor_new(((ent__Actor)r0),r6,r8,r10);
	r12 = r0->game;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->wallSprites;
	if( r11 == NULL ) hl_null_access();
	r3 = 0;
	r13 = r11->length;
	if( ((unsigned)r3) < ((unsigned)r13) ) goto label$166ddd8_2_19;
	r11 = NULL;
	goto label$166ddd8_2_22;
	label$166ddd8_2_19:
	r15 = r11->array;
	r14 = ((vdynamic**)(r15 + 1))[r3];
	r11 = (hl__types__ArrayObj)hl_dyn_castp(&r14,&t$_dyn,&t$hl_types_ArrayObj);
	label$166ddd8_2_22:
	if( r11 == NULL ) hl_null_access();
	r3 = 0;
	r13 = r11->length;
	if( ((unsigned)r3) < ((unsigned)r13) ) goto label$166ddd8_2_28;
	r16 = NULL;
	goto label$166ddd8_2_34;
	label$166ddd8_2_28:
	r15 = r11->array;
	r14 = ((vdynamic**)(r15 + 1))[r3];
	r16 = (h2d__Tile)r14;
	r17 = (h2d__Tile)hl_dyn_castp(&r14,&t$_dyn,&t$h2d_Tile);
	if( r16 == r17 ) goto label$166ddd8_2_34;
	hl_assert();
	label$166ddd8_2_34:
	r0->tile = r16;
	r18 = (h2d__Bitmap)hl_alloc_obj(&t$h2d_Bitmap);
	r16 = r0->tile;
	r19 = r0->spr;
	h2d_Bitmap_new(r18,r16,r19);
	r0->bmp = r18;
	r12 = r0->game;
	if( r12 == NULL ) hl_null_access();
	r20 = r12->scene;
	if( r20 == NULL ) hl_null_access();
	r19 = r0->spr;
	h2d_Layers_addChild(((h2d__Layers)r20),r19);
	return;
}

